# Generated by Django 5.1 on 2024-08-30 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_submission_file_remove_submission_uploaded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='last_name',
        ),
        migrations.AddField(
            model_name='submission',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
