# Generated by Django 5.1 on 2024-08-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_submission_description_alter_submission_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
